#
# Makefile for all kinds of Fingerprint
#
obj-$(CONFIG_SUNWAVE_TEE_FINGERPRINT) += sunwave_fp_tee/
#obj-$(CONFIG_GOODIX_FINGERPRINT) += goodix/
#obj-$(CONFIG_FPC_FINGERPRINT) += fpc/
obj-$(CONFIG_FINGERPRINT_GOODIX) += goodix/
obj-$(CONFIG_FINGERPRINT_FPC) += fpc/
obj-$(CONFIG_FINGERPRINT_CDFINGER) += cdfinger/
obj-$(CONFIG_FINGERPRINT_FOCALTECH) += focaltech/
obj-$(CONFIG_FINGERPRINT_EGISTEC) += egistec/
obj-$(CONFIG_FINGERPRINT_EGISTEC_FOD) += egistec_fod/
