#
## Makefile for the touchscreen drivers.
#
#
## Each configuration option enables a list of files.
ccflags-y += -I$(srctree)/drivers/input/touchscreen/ILI7807Q/

obj-$(CONFIG_TOUCHSCREEN_ILI7807Q)	+= touch_ili7807q.o
obj-$(CONFIG_TOUCHSCREEN_ILI7807Q)	+= touch_ili7807q_fw.o
obj-$(CONFIG_TOUCHSCREEN_ILI7807Q)	+= touch_ili7807q_mp.o
obj-$(CONFIG_TOUCHSCREEN_ILI7807Q)	+= touch_ili7807q_apk.o
obj-$(CONFIG_TOUCHSCREEN_ILI7807Q)	+= touch_i2c.o
obj-$(CONFIG_TOUCHSCREEN_ILI7807Q)	+= touch_spi.o
obj-$(CONFIG_TOUCHSCREEN_ILI7807Q)	+= touch_notify.o
obj-$(CONFIG_TOUCHSCREEN_ILI7807Q)	+= touch_core.o
obj-$(CONFIG_TOUCHSCREEN_ILI7807Q)	+= touch_common.o
obj-$(CONFIG_TOUCHSCREEN_ILI7807Q)	+= touch_model.o
obj-$(CONFIG_TOUCHSCREEN_ILI7807Q)	+= touch_core_sysfs.o
obj-$(CONFIG_TOUCHSCREEN_ILI7807Q)	+= touch_module_builtIn.o
obj-$(CONFIG_TOUCHSCREEN_ILI7807Q)	+= touch_hwif.o