#ccflags-y				+= -DDEBUG
#ccflags-y				+= -DVERBOSE_DEBUG
subdir-ccflags-y += -I$(srctree)/drivers/misc/mediatek/base/power/include/srclken_rc_v1/mt6885/

obj-$(CONFIG_LGE_USB_LATTICE_SLS11HC)	+= sls11hc.o
sls11hc-y := core.o sls-hcd.o
