# defines
# FIRMWARE_PROFILE : test for firmware wrting time
# PD_DEBUG : test for pd send timeout
# PD_CTS_TEST : for PD CTS

obj-$(CONFIG_LGE_USB_TUSB546) := tusb546.o
obj-$(CONFIG_LGE_USB_TUSB546) += tusb546_i2c.o
obj-$(CONFIG_LGE_USB_TUSB546) += tusb546_debugfs.o

